### PR TITLE
Update pktgen version to 3.6.5

### PR DESCRIPTION
**Pull request by koolzz**
Updates the pktgen version 3.6.5

Fixes our lua issue

### CODE REVIEW

**Comment by koolzz** [comment]
@nks5295 Is this the proper way to do this? I rebased our code on top but as a pr its weird. But it has other ppl commits and no new commits from us

**Comment by nks5295** [comment]
Yes, our code should always be on top of theirs as it does not interfere with the pktgen itself.

**Comment by nks5295** [comment]
once this is merged, then we need to update the pktgen submod ptr in opennetvm repo to the latest commit sha on the onvm branch

**Comment by nks5295** [comment]
i'll submit this if it's good to go

**Comment by nks5295** [comment]
@koolzz said it's all good

**Comment by koolzz** [comment]
Replaced with #8

**Pull request closed without merging**
