### PR TITLE
Update pktgen version to work with dpdk 17.08

### PR DESCRIPTION
**Pull request by rskennedy**
Pull most recent code from dpdk-pktgen master to work with openNetVM's version of DPDK.

__Problem__: pktgen version was outdated and relied on older APIs that DPDK had since moved away from. This produced compile errors.
__Solution:__ Pull most recent code from pktgen upstream.

### CODE REVIEW

**Comment by twood02** [comment]
have you verified this works with DPDK 17.08 and doesn't require even newer versions like 18.01?

**Comment by rskennedy** [comment]
My testing setup uses the 17.08 version of DPDK from openNetVM. I will test again but I don't believe there will be any problems.

**Comment by twood02** [comment]
OK, this is ready to merge then.

**Review by nks5295 — APPROVED** [review]

**Comment by twood02** [comment]
@nks5295 -- will squashing this cause problems for when we want to bring in future pktgen updates? Is it better to preserve all the commit history?

(I don't know if it matters)

**Comment by nks5295** [comment]
Nope, I sync'd the branches properly against Pktgen upstream master first to preserve their commit history and ours.  This squash commit will be more like a "message" indicating that we bumped the version number.

I will be posting a note to our slack channel on how to update onvm-dpdk and onvm-pktgen as we have not been doing it the right way.

**Comment by twood02** [comment]
great, good to know.

**Pull request merged**
